// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheBookHeaven;

#nullable disable

namespace TheBookHeaven.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20250612152845_UpdateBookImages")]
    partial class UpdateBookImages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TheBookHeaven.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Best Sellers",
                            ImageUrl = "/images/book1.jpeg",
                            Price = 19.99m,
                            Title = "Little Women"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Fiction",
                            ImageUrl = "/images/book2.jpeg",
                            Price = 14.99m,
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Non-Fiction",
                            ImageUrl = "/images/book3.jpeg",
                            Price = 21.50m,
                            Title = "Sapiens"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
