// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheBookHeaven;

#nullable disable

namespace TheBookHeaven.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20250627012035_SeedMoreBooks")]
    partial class SeedMoreBooks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TheBookHeaven.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Best Sellers",
                            ImageUrl = "https://cdn.britannica.com/04/126004-050-EC4DF54F/Dustcover-Louisa-May-Alcott-Little-Women-novel.jpg",
                            Price = 19.99m,
                            Title = "Little Women"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Best Sellers",
                            ImageUrl = "https://m.media-amazon.com/images/I/71ls-I6A5KL.jpg",
                            Price = 17.99m,
                            Title = "The Midnight Library"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Best Sellers",
                            ImageUrl = "https://m.media-amazon.com/images/I/81e+mSqZvnL._UF1000,1000_QL80_.jpg",
                            Price = 16.50m,
                            Title = "Where the Crawdads Sing"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Best Sellers",
                            ImageUrl = "https://m.media-amazon.com/images/I/612KmKeEYEL._UF1000,1000_QL80_.jpg",
                            Price = 17.25m,
                            Title = "Crime and Punishment"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Fiction",
                            ImageUrl = "https://assets.lulu.com/cover_thumbs/8/d/8dzdnj-front-shortedge-384.jpg",
                            Price = 14.99m,
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Fiction",
                            ImageUrl = "https://bci.kinokuniya.com/jsp/images/book-img/97801/97801410/9780141036144.JPG",
                            Price = 15.00m,
                            Title = "1984"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Fiction",
                            ImageUrl = "https://m.media-amazon.com/images/I/81aY1lxk+9L.jpg",
                            Price = 13.50m,
                            Title = "To Kill a Mockingbird"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Fiction",
                            ImageUrl = "https://cdn.kobo.com/book-images/fdeeeaac-142d-44fc-8484-698fcf5e6378/1200/1200/False/the-overcoat-and-other-short-stories.jpg",
                            Price = 11.99m,
                            Title = "The Overcoat and Other Short Stories"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Non-Fiction",
                            ImageUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1703329310i/23692271.jpg",
                            Price = 21.50m,
                            Title = "Sapiens"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Non-Fiction",
                            ImageUrl = "https://m.media-amazon.com/images/I/71N2HZwRo3L.jpg",
                            Price = 18.99m,
                            Title = "Educated"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Non-Fiction",
                            ImageUrl = "https://m.media-amazon.com/images/I/81ANaVZk5LL.jpg",
                            Price = 20.99m,
                            Title = "Atomic Habits"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Non-Fiction",
                            ImageUrl = "https://m.media-amazon.com/images/I/71wm29Etl4L.jpg",
                            Price = 16.95m,
                            Title = "The Power of Habit"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
